### ISSUE TITLE
IE8 下css兼容问题

### ISSUE THREAD

**Issue by gaomysion** [imingyu/jquery.mloading#1]
### 问题描述
1. 环境：windows7自带的IE8
2. 现象：插件自带的demo没有问题。
3. 项目中使用的sea.js,将loading插件加入后，IE8下添加了插件的页面可以正常展示，但是页面上的点击事件全部失效，查看过后发现插件自带的css样式文件根本没有加载，或者加载时有问题，IE8 F12控制台啥错也没得。
4. 把css样式注释后，功能都正常，但是loading效果也没了，查看了半天也没发现哪个css有问题。希望看看。。

**Comment by imingyu** [comment]
那link到页面上的css文件是否路径正确？
