### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by EEEVO** [imingyu/jquery.mloading#3]
在页面初始化时插件触发show有效,但是一旦查询事件进入show就无效(查询传的sql,可能数据量比较大导致,目前是7W条)

**Comment by imingyu** [comment]
【一旦查询事件进入show】是何意？

本插件只是在前端显示和隐藏一个遮罩div而已，跟数据量大不大、查不查询SQL无关，只跟你什么时候调用show和hide方法有关。

**Comment by EEEVO** [comment]
是我自己的问题,数据量大了浏览器性能跟不上于是show()了无效.谢谢回复
